### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by xenoner1506** [Ponamarev/Infa_2021_Ponamarev#1]
Some notes about 1week exercises:

1. Don't make extra spaces between namespace and function (for example, `std::cin` or  `std::cout`)
2. Forget about `float`. You can use `double`.
3.  `Rect.cpp` makes squares with side `n+1`.
4. `triangle.cpp` makes triangles with side `n+1`.
5. `Back_triangle.cpp` makes triangles with side `n+1`.
6. If you write `for/while` loop or `if-else` statement don't forget to make space between statement and bracket (`for (int i = 0; i < 10; i++) {`/`} else {`)
7.  If you write `{` in line with a loop statement, then you must make it for all functions (for main() too).

**Comment by Ponamarev** [comment]
All mistakes fixed.
